### ISSUE TITLE
Kullanıcıların bloglarının sitede gösterilmesi

### ISSUE THREAD

**Issue by jeffisabelle** [pyistanbul/website#11]
Merhaba, 

RSS speclerini çok bilmiyorum, ama şöyle bir fikrim var, insanlar kısmında blog bilgilerini giren kullanıcıların rss'leri düzenli olarak parse edilip, insanlar kısmında son yazılan ve kategorisi python olan blog yazıları gösterilebilir mi? 

bi nevi gezegen gibi ama siteyle integre olcak şekilde. ya da blog yazarları postlara bi event trigger edecek bi kod parçası ekleyip yazdıkları blogların sistemde görünmesini sağlayabilirler gibi, hergün düzenli parse etmekten daha az masraflı olabilir, bilemedim.

**Comment by berkerpeksag** [comment]
Bunu kapatıyorum. Aradan geçen yaklaşık 2 yıldan da görüldüğü üzere bu tartışmaya katılanlar bile düzenli blog yazmıyorlar :)
