### ISSUE TITLE
Radpress'ten el yapımı basit bir blog uygulamasına geçiş

### ISSUE THREAD

**Issue by berkerpeksag** [pyistanbul/website#41]
Migrationlar patlıyor, Python 3 desteği yok. 1 modellik işi var blog sayfasının bizim ihtiyaçlarımıza göre.

**Comment by bahattincinic** [comment]
isterseniz ben yazabilirim. Olmasi gereken ozellikleri belirtilin haftasonu baslarim yapmaya.

**Comment by fatiherikli** [comment]
Arguman'in blog app'ini kullanabiliriz. Aynisini kisisel sitemde ve dbpatterns'ta da kullaniyorum.

https://github.com/arguman/arguman.org/tree/master/web/blog

**Comment by berkerpeksag** [comment]
Evet arguman.org'un blog app'ini kullanabiliriz. Mevcut blog postları bu app'e taşıyacak bir migration/command/standalone script vb. bonus olur :)

**Comment by emre** [comment]
:+1:

**Comment by fatiherikli** [comment]
Script'e gerek yok ya elimizle yapariz. Fazla blog post'u yok zaten.

**Comment by berkerpeksag** [comment]
oo content editor erikli :trollface:

**Comment by fatiherikli** [comment]
Haha okay ben hallederim o kısmı. Bahattin sen bakabilir misin buna haftasonu?

**Comment by bahattincinic** [comment]
Tamamdir ben haftasonu bakarim.

**Comment by berkerpeksag** [comment]
@bahattincinic bu issue'ya bakmak için zamanın var mı?

**Comment by bahattincinic** [comment]
@berkerpeksag buyuk bir kismini yazdim dun. Gondericem bugun yarin :smile:

**Comment by berkerpeksag** [comment]
Blog app'i ve Django 1.7 güncellemesi master'da: https://github.com/pyistanbul/website/commit/c9a1fe217596082350a04092b66bb65a34b9137c ve https://github.com/pyistanbul/website/commit/ef34a19b01c1525c27a94bad8124fdb8f61b646f

Deploy etmedim, yazıları taşımayı hallettikten sonra edeceğim.

**Comment by fatiherikli** [comment]
@berkerpeksag yazıları nasıl taşıyayım?

**Comment by berkerpeksag** [comment]
django master sensin aybalam, nasıl uygunsa öyle yapalım. gerekirse sunucu bilgilerini vereyim

**Comment by emre** [comment]
<img src="http://i.imgur.com/FfnEYmU.png">
