### ISSUE TITLE
Fontawesome entegrasyonu yaptım

### ISSUE THREAD

**Issue by vigo** [pyistanbul/website#42]
Arkadaşlar, şöyle birşey yaptım:

Öncesi:

![Before](http://i.imgur.com/5Tq1ASn.png)

Sonrası:

![After](http://i.imgur.com/G1HZIh5.png)

Basit bir templatetag yazdım. Local'de ayrı bir branch'de. Ne yapayım o branch'i push edeyimmi? yoksa fork/pr mi gideyim? Sanırım access yetkim var direk merge/push da yapabilirim? Hata olmaması açısından ne yapayım?

**Comment by vigo** [comment]
yaklaşık 2 ay geçti, ne oldu halen merge'ü bekliyoruz? bu ne hantal komünite, yöneticimiz uyuyormu? izocaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaam?

**Comment by cihann** [comment]
@berkerpeksag kardes NE DURUMDAYIZ?

**Comment by berkerpeksag** [comment]
haftasonu

**Comment by berkerpeksag** [comment]
bugün yayına alıyorum bunu ve hakkında sayfasına markdown desteğini. hakkında sayfası için 1 paragraflık 1-2 paragraf karalamak isteyen var mı? :)

**Comment by berkerpeksag** [comment]
Nihayet: https://github.com/pyistanbul/website/commit/1c11667e612bcac2e1c31fabbe33ffbeb861df68 ve http://pyistanbul.org/people/

Gecikme için kusuruma bakma @vigo reyis, AMİGAAAAAAAAA :)

**Comment by vigo** [comment]
hahahahahaha ok kardeşim, amiga dedinya kalbimi bir kez daha feth ettin :)

**Comment by fatiherikli** [comment]
Ben de bir duzenleme yaptım ancak pull-request yerine direkt commit'ledim yanlislikla github uzerinden.

Fonk-awesome ikonlarini altta sabitledim son commit'le.

**Comment by berkerpeksag** [comment]
deployu yapıştırdım aybalam
