### ISSUE TITLE
Add .tox folder to gitignore

### ISSUE THREAD

**Issue by mastizada** [pyistanbul/website#70]

**Comment by berkerpeksag** [comment]
Bu tip her Python projesinde `.gitignore`'a eklenecek şeyleri [global bir `.gitignore`](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) dosyasında tutmak daha iyi bence. Bu issue'yu da bizim `.gitignore`'u sadeleştirmek için kullanabiliriz.

Aşağıdakiler haricindeki her şeyi uçurabiliriz:

```py
settings_local.py
fabenv.py
```
