### ISSUE TITLE
Upgrade to latest Django

### ISSUE THREAD

**Issue by vigo** [pyistanbul/website#75]
We need to upgrade Django 2+ plus fix unsecure packages (gunicorn etc...)

**Comment by bahattincinic** [comment]
https://github.com/pyistanbul/website/tree/cleanup branch inda yukseltildi Django ve gunicorn.

**Comment by berkerpeksag** [comment]
Bahattin haklı, cleanup branch'inde Django ve Gunicorn versiyonları güncellendi. Yeni tasarımla beraber cleanup branch'ini içeri alacağız. O yüzden şimdilik kapatıyorum bu issue'yu.
